name: MSBuild

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build_and_test_vs2022:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: nuget restore ./prj/vs2022 -Project2ProjectTimeOut 300

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=Release /p:Platform=x64 -maxCpuCount:4 ./prj/vs2022/Simd.sln

      - name: Test
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: bin/v143/x64/Release/Test.exe "-r=." -m=a -tt=-1 "-ot=log_x64_Release.txt" -ts=10

      - name: Upload Simd.dll
        uses: actions/upload-artifact@v3
        with:
          name: Simd-x64-Release
          path: bin/v143/x64/Release/Simd.dll
